// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKP7o2BUFNDIrpBEzfuQe1BcdDiEGvAuE',
    appId: '1:29827939205:web:f37e072ed456d75f9f62ec',
    messagingSenderId: '29827939205',
    projectId: 'python-169a6',
    authDomain: 'python-169a6.firebaseapp.com',
    storageBucket: 'python-169a6.firebasestorage.app',
    measurementId: 'G-MLG1VQ7MGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYveqOmfn7pkBDn_X_cm-bklX0lUAFMXU',
    appId: '1:29827939205:android:f542cd65d57046d59f62ec',
    messagingSenderId: '29827939205',
    projectId: 'python-169a6',
    storageBucket: 'python-169a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu-9FRFetplNMIQLi6UjJxLA3FH05Komg',
    appId: '1:29827939205:ios:10549f59bdf056b79f62ec',
    messagingSenderId: '29827939205',
    projectId: 'python-169a6',
    storageBucket: 'python-169a6.firebasestorage.app',
    iosBundleId: 'com.example.python',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu-9FRFetplNMIQLi6UjJxLA3FH05Komg',
    appId: '1:29827939205:ios:10549f59bdf056b79f62ec',
    messagingSenderId: '29827939205',
    projectId: 'python-169a6',
    storageBucket: 'python-169a6.firebasestorage.app',
    iosBundleId: 'com.example.python',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKP7o2BUFNDIrpBEzfuQe1BcdDiEGvAuE',
    appId: '1:29827939205:web:ec836c4aa86be13e9f62ec',
    messagingSenderId: '29827939205',
    projectId: 'python-169a6',
    authDomain: 'python-169a6.firebaseapp.com',
    storageBucket: 'python-169a6.firebasestorage.app',
    measurementId: 'G-Z78588Q1S0',
  );
}
